### ISSUE TITLE
Should I use histogram matching or normalization for pre-processing?

### ISSUE THREAD

**Issue by John1231983** [ntustison/ANTsRNet#3]
Considering brain MRI segmentation, should I use (1) histogram matching to match the distribution of all images with an image (selected as a template) or (2) just normalize these images to zero mean and unit variance. Which option do you prefer? I often see many papers use the second option although both of them use to rescale intensity image to the same range.

Thanks

**Comment by ntustison** [comment]
This particular repo is outdated.  [Here](https://github.com/ANTsRNet) is where we are currently putting the examples with direct access to the trained models.  For the brain segmentation app we used 2).

**Comment by John1231983** [comment]
Thanks for your reply. Could you please tell me what is benefit of second approach in comparison with first one. Both of them are used to rescale to same range

**Comment by ntustison** [comment]
We haven't done any sort of comparison between the two normalization methods.  However, the latter is common and very easy to calculate.
